# DigitalOcean App Platform Configuration - STAGING ENVIRONMENT
# Deploy Instantly MCP Server for testing and validation
name: Instantly MCP Staging
region: nyc

services:
- name: mcp-server-staging
  source_dir: /
  github:
    repo: bcharleson/Instantly-MCP
    branch: main
    deploy_on_push: true

  # Build configuration - explicitly use buildpacks, not Docker
  build_command: npm ci && npm run build

  # Runtime configuration
  run_command: npm run start:production
  
  # Environment configuration
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Environment variables
  envs:
  - key: NODE_ENV
    value: staging
  - key: TRANSPORT_MODE
    value: http
  - key: PORT
    value: "8080"
  - key: HOST
    value: "0.0.0.0"
  - key: ENVIRONMENT
    value: staging
  
  # Health check configuration
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # HTTP configuration
  http_port: 8080
  
  # Routes configuration
  routes:
  - path: /
    preserve_path_prefix: true

# Alerts configuration (less strict for staging)
alerts:
- rule: CPU_UTILIZATION
  disabled: false
  value: 90
- rule: MEM_UTILIZATION
  disabled: false
  value: 90
- rule: RESTART_COUNT
  disabled: false
  value: 10

# Database configuration (none needed for this stateless service)
databases: []

# Static sites configuration (none needed)
static_sites: []

# Workers configuration (none needed)
workers: []

# Jobs configuration (none needed)
jobs: []
